/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as SapCoverageRouteImport } from './routes/sap-coverage'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAllowlistRouteImport } from './routes/dashboard/allowlist'
import { Route as DashboardAuditRouteImport } from './routes/dashboard/audit'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard/compliance'
import { Route as DashboardFindingsRouteImport } from './routes/dashboard/findings'
import { Route as DashboardIdentityRouteImport } from './routes/dashboard/identity'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard/integrations'
import { Route as DashboardPolicyRouteImport } from './routes/dashboard/policy'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardQuarantineRouteImport } from './routes/dashboard/quarantine'
import { Route as DashboardSbomRouteImport } from './routes/dashboard/sbom'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as ApiV1ScansRouteImport } from './routes/api/v1/scans'
import { Route as ApiWorkerHeartbeatRouteImport } from './routes/api/worker/heartbeat'
import { Route as DashboardBuildsIndexRouteImport } from './routes/dashboard/builds/index'
import { Route as DashboardBuildsBuildIdRouteImport } from './routes/dashboard/builds/$buildId'
import { Route as DashboardWorkersIndexRouteImport } from './routes/dashboard/workers/index'
import { Route as DashboardWorkersInstallRouteImport } from './routes/dashboard/workers/install'
import { Route as ApiV1ComplianceCodeRouteImport } from './routes/api/v1/compliance/$code'
import { Route as ApiV1ExportKindRouteImport } from './routes/api/v1/export/$kind'
import { Route as ApiV1BuildsIdIndexRouteImport } from './routes/api/v1/builds/$id/index'
import { Route as ApiV1BuildsIdArtifactRouteImport } from './routes/api/v1/builds/$id/$artifact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SapCoverageRoute = SapCoverageRouteImport.update({
  id: '/sap-coverage',
  path: '/sap-coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAllowlistRoute = DashboardAllowlistRouteImport.update({
  id: '/allowlist',
  path: '/allowlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFindingsRoute = DashboardFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIdentityRoute = DashboardIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPolicyRoute = DashboardPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuarantineRoute = DashboardQuarantineRouteImport.update({
  id: '/quarantine',
  path: '/quarantine',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSbomRoute = DashboardSbomRouteImport.update({
  id: '/sbom',
  path: '/sbom',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiV1ScansRoute = ApiV1ScansRouteImport.update({
  id: '/api/v1/scans',
  path: '/api/v1/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkerHeartbeatRoute = ApiWorkerHeartbeatRouteImport.update({
  id: '/api/worker/heartbeat',
  path: '/api/worker/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuildsIndexRoute = DashboardBuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuildsBuildIdRoute = DashboardBuildsBuildIdRouteImport.update({
  id: '/builds/$buildId',
  path: '/builds/$buildId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkersIndexRoute = DashboardWorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkersInstallRoute = DashboardWorkersInstallRouteImport.update({
  id: '/workers/install',
  path: '/workers/install',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiV1ComplianceCodeRoute = ApiV1ComplianceCodeRouteImport.update({
  id: '/api/v1/compliance/$code',
  path: '/api/v1/compliance/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportKindRoute = ApiV1ExportKindRouteImport.update({
  id: '/api/v1/export/$kind',
  path: '/api/v1/export/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BuildsIdIndexRoute = ApiV1BuildsIdIndexRouteImport.update({
  id: '/api/v1/builds/$id/',
  path: '/api/v1/builds/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BuildsIdArtifactRoute = ApiV1BuildsIdArtifactRouteImport.update({
  id: '/api/v1/builds/$id/$artifact',
  path: '/api/v1/builds/$id/$artifact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/compliance': typeof ComplianceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/sap-coverage': typeof SapCoverageRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/allowlist': typeof DashboardAllowlistRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/findings': typeof DashboardFindingsRoute
  '/dashboard/identity': typeof DashboardIdentityRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/policy': typeof DashboardPolicyRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/quarantine': typeof DashboardQuarantineRoute
  '/dashboard/sbom': typeof DashboardSbomRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/v1/scans': typeof ApiV1ScansRoute
  '/api/worker/heartbeat': typeof ApiWorkerHeartbeatRoute
  '/dashboard/builds/$buildId': typeof DashboardBuildsBuildIdRoute
  '/dashboard/workers/install': typeof DashboardWorkersInstallRoute
  '/dashboard/builds/': typeof DashboardBuildsIndexRoute
  '/dashboard/workers/': typeof DashboardWorkersIndexRoute
  '/api/v1/compliance/$code': typeof ApiV1ComplianceCodeRoute
  '/api/v1/export/$kind': typeof ApiV1ExportKindRoute
  '/api/v1/builds/$id/$artifact': typeof ApiV1BuildsIdArtifactRoute
  '/api/v1/builds/$id/': typeof ApiV1BuildsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/compliance': typeof ComplianceRoute
  '/customers': typeof CustomersRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/sap-coverage': typeof SapCoverageRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/allowlist': typeof DashboardAllowlistRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/findings': typeof DashboardFindingsRoute
  '/dashboard/identity': typeof DashboardIdentityRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/policy': typeof DashboardPolicyRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/quarantine': typeof DashboardQuarantineRoute
  '/dashboard/sbom': typeof DashboardSbomRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/v1/scans': typeof ApiV1ScansRoute
  '/api/worker/heartbeat': typeof ApiWorkerHeartbeatRoute
  '/dashboard/builds/$buildId': typeof DashboardBuildsBuildIdRoute
  '/dashboard/workers/install': typeof DashboardWorkersInstallRoute
  '/dashboard/builds': typeof DashboardBuildsIndexRoute
  '/dashboard/workers': typeof DashboardWorkersIndexRoute
  '/api/v1/compliance/$code': typeof ApiV1ComplianceCodeRoute
  '/api/v1/export/$kind': typeof ApiV1ExportKindRoute
  '/api/v1/builds/$id/$artifact': typeof ApiV1BuildsIdArtifactRoute
  '/api/v1/builds/$id': typeof ApiV1BuildsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/compliance': typeof ComplianceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRoute
  '/sap-coverage': typeof SapCoverageRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/allowlist': typeof DashboardAllowlistRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/findings': typeof DashboardFindingsRoute
  '/dashboard/identity': typeof DashboardIdentityRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/policy': typeof DashboardPolicyRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/quarantine': typeof DashboardQuarantineRoute
  '/dashboard/sbom': typeof DashboardSbomRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/v1/scans': typeof ApiV1ScansRoute
  '/api/worker/heartbeat': typeof ApiWorkerHeartbeatRoute
  '/dashboard/builds/$buildId': typeof DashboardBuildsBuildIdRoute
  '/dashboard/workers/install': typeof DashboardWorkersInstallRoute
  '/dashboard/builds/': typeof DashboardBuildsIndexRoute
  '/dashboard/workers/': typeof DashboardWorkersIndexRoute
  '/api/v1/compliance/$code': typeof ApiV1ComplianceCodeRoute
  '/api/v1/export/$kind': typeof ApiV1ExportKindRoute
  '/api/v1/builds/$id/$artifact': typeof ApiV1BuildsIdArtifactRoute
  '/api/v1/builds/$id/': typeof ApiV1BuildsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/compliance'
    | '/customers'
    | '/dashboard'
    | '/demo'
    | '/docs'
    | '/login'
    | '/policies'
    | '/sap-coverage'
    | '/signup'
    | '/api/health'
    | '/dashboard/allowlist'
    | '/dashboard/audit'
    | '/dashboard/compliance'
    | '/dashboard/findings'
    | '/dashboard/identity'
    | '/dashboard/integrations'
    | '/dashboard/policy'
    | '/dashboard/projects'
    | '/dashboard/quarantine'
    | '/dashboard/sbom'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/v1/scans'
    | '/api/worker/heartbeat'
    | '/dashboard/builds/$buildId'
    | '/dashboard/workers/install'
    | '/dashboard/builds/'
    | '/dashboard/workers/'
    | '/api/v1/compliance/$code'
    | '/api/v1/export/$kind'
    | '/api/v1/builds/$id/$artifact'
    | '/api/v1/builds/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/compliance'
    | '/customers'
    | '/demo'
    | '/docs'
    | '/login'
    | '/policies'
    | '/sap-coverage'
    | '/signup'
    | '/api/health'
    | '/dashboard/allowlist'
    | '/dashboard/audit'
    | '/dashboard/compliance'
    | '/dashboard/findings'
    | '/dashboard/identity'
    | '/dashboard/integrations'
    | '/dashboard/policy'
    | '/dashboard/projects'
    | '/dashboard/quarantine'
    | '/dashboard/sbom'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/v1/scans'
    | '/api/worker/heartbeat'
    | '/dashboard/builds/$buildId'
    | '/dashboard/workers/install'
    | '/dashboard/builds'
    | '/dashboard/workers'
    | '/api/v1/compliance/$code'
    | '/api/v1/export/$kind'
    | '/api/v1/builds/$id/$artifact'
    | '/api/v1/builds/$id'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/compliance'
    | '/customers'
    | '/dashboard'
    | '/demo'
    | '/docs'
    | '/login'
    | '/policies'
    | '/sap-coverage'
    | '/signup'
    | '/api/health'
    | '/dashboard/allowlist'
    | '/dashboard/audit'
    | '/dashboard/compliance'
    | '/dashboard/findings'
    | '/dashboard/identity'
    | '/dashboard/integrations'
    | '/dashboard/policy'
    | '/dashboard/projects'
    | '/dashboard/quarantine'
    | '/dashboard/sbom'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/v1/scans'
    | '/api/worker/heartbeat'
    | '/dashboard/builds/$buildId'
    | '/dashboard/workers/install'
    | '/dashboard/builds/'
    | '/dashboard/workers/'
    | '/api/v1/compliance/$code'
    | '/api/v1/export/$kind'
    | '/api/v1/builds/$id/$artifact'
    | '/api/v1/builds/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ComplianceRoute: typeof ComplianceRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  PoliciesRoute: typeof PoliciesRoute
  SapCoverageRoute: typeof SapCoverageRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiV1ScansRoute: typeof ApiV1ScansRoute
  ApiWorkerHeartbeatRoute: typeof ApiWorkerHeartbeatRoute
  ApiV1ComplianceCodeRoute: typeof ApiV1ComplianceCodeRoute
  ApiV1ExportKindRoute: typeof ApiV1ExportKindRoute
  ApiV1BuildsIdArtifactRoute: typeof ApiV1BuildsIdArtifactRoute
  ApiV1BuildsIdIndexRoute: typeof ApiV1BuildsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sap-coverage': {
      id: '/sap-coverage'
      path: '/sap-coverage'
      fullPath: '/sap-coverage'
      preLoaderRoute: typeof SapCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/allowlist': {
      id: '/dashboard/allowlist'
      path: '/allowlist'
      fullPath: '/dashboard/allowlist'
      preLoaderRoute: typeof DashboardAllowlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/findings': {
      id: '/dashboard/findings'
      path: '/findings'
      fullPath: '/dashboard/findings'
      preLoaderRoute: typeof DashboardFindingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/identity': {
      id: '/dashboard/identity'
      path: '/identity'
      fullPath: '/dashboard/identity'
      preLoaderRoute: typeof DashboardIdentityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/policy': {
      id: '/dashboard/policy'
      path: '/policy'
      fullPath: '/dashboard/policy'
      preLoaderRoute: typeof DashboardPolicyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quarantine': {
      id: '/dashboard/quarantine'
      path: '/quarantine'
      fullPath: '/dashboard/quarantine'
      preLoaderRoute: typeof DashboardQuarantineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sbom': {
      id: '/dashboard/sbom'
      path: '/sbom'
      fullPath: '/dashboard/sbom'
      preLoaderRoute: typeof DashboardSbomRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/v1/scans': {
      id: '/api/v1/scans'
      path: '/api/v1/scans'
      fullPath: '/api/v1/scans'
      preLoaderRoute: typeof ApiV1ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worker/heartbeat': {
      id: '/api/worker/heartbeat'
      path: '/api/worker/heartbeat'
      fullPath: '/api/worker/heartbeat'
      preLoaderRoute: typeof ApiWorkerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/builds/': {
      id: '/dashboard/builds/'
      path: '/builds'
      fullPath: '/dashboard/builds/'
      preLoaderRoute: typeof DashboardBuildsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/builds/$buildId': {
      id: '/dashboard/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/dashboard/builds/$buildId'
      preLoaderRoute: typeof DashboardBuildsBuildIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workers/': {
      id: '/dashboard/workers/'
      path: '/workers'
      fullPath: '/dashboard/workers/'
      preLoaderRoute: typeof DashboardWorkersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workers/install': {
      id: '/dashboard/workers/install'
      path: '/workers/install'
      fullPath: '/dashboard/workers/install'
      preLoaderRoute: typeof DashboardWorkersInstallRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/v1/compliance/$code': {
      id: '/api/v1/compliance/$code'
      path: '/api/v1/compliance/$code'
      fullPath: '/api/v1/compliance/$code'
      preLoaderRoute: typeof ApiV1ComplianceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/export/$kind': {
      id: '/api/v1/export/$kind'
      path: '/api/v1/export/$kind'
      fullPath: '/api/v1/export/$kind'
      preLoaderRoute: typeof ApiV1ExportKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/builds/$id/': {
      id: '/api/v1/builds/$id/'
      path: '/api/v1/builds/$id'
      fullPath: '/api/v1/builds/$id/'
      preLoaderRoute: typeof ApiV1BuildsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/builds/$id/$artifact': {
      id: '/api/v1/builds/$id/$artifact'
      path: '/api/v1/builds/$id/$artifact'
      fullPath: '/api/v1/builds/$id/$artifact'
      preLoaderRoute: typeof ApiV1BuildsIdArtifactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAllowlistRoute: typeof DashboardAllowlistRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardFindingsRoute: typeof DashboardFindingsRoute
  DashboardIdentityRoute: typeof DashboardIdentityRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardPolicyRoute: typeof DashboardPolicyRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardQuarantineRoute: typeof DashboardQuarantineRoute
  DashboardSbomRoute: typeof DashboardSbomRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBuildsBuildIdRoute: typeof DashboardBuildsBuildIdRoute
  DashboardWorkersInstallRoute: typeof DashboardWorkersInstallRoute
  DashboardBuildsIndexRoute: typeof DashboardBuildsIndexRoute
  DashboardWorkersIndexRoute: typeof DashboardWorkersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAllowlistRoute: DashboardAllowlistRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardFindingsRoute: DashboardFindingsRoute,
  DashboardIdentityRoute: DashboardIdentityRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardPolicyRoute: DashboardPolicyRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardQuarantineRoute: DashboardQuarantineRoute,
  DashboardSbomRoute: DashboardSbomRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBuildsBuildIdRoute: DashboardBuildsBuildIdRoute,
  DashboardWorkersInstallRoute: DashboardWorkersInstallRoute,
  DashboardBuildsIndexRoute: DashboardBuildsIndexRoute,
  DashboardWorkersIndexRoute: DashboardWorkersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  ComplianceRoute: ComplianceRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  PoliciesRoute: PoliciesRoute,
  SapCoverageRoute: SapCoverageRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiV1ScansRoute: ApiV1ScansRoute,
  ApiWorkerHeartbeatRoute: ApiWorkerHeartbeatRoute,
  ApiV1ComplianceCodeRoute: ApiV1ComplianceCodeRoute,
  ApiV1ExportKindRoute: ApiV1ExportKindRoute,
  ApiV1BuildsIdArtifactRoute: ApiV1BuildsIdArtifactRoute,
  ApiV1BuildsIdIndexRoute: ApiV1BuildsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
